### ISSUE TITLE
Border type not updating

### ISSUE THREAD

**Issue by Thrayl** [enolgor/wow-addon-tiptac#1]
No matter what style of border you select, you only ever get the default.

**Comment by Architekt909** [comment]
Same goes for background type (note that changing bg color works fine)

**Comment by enolgor** [comment]
Does it work if after changing the border you /reload?

**Comment by Thrayl** [comment]
Unfortunately it does not.

**Comment by enolgor** [comment]
I'm trying to figure out why the backdrop is not updating, I've checked and played around with [this function call](https://github.com/enolgor/wow-addon-tiptac/blob/3f9dc82db40b566aaa17d1a22306d8d1593c2d83/TipTac/ttCore.lua#L518) and  some hooks where it's supposed to call ApplyBackdrop like [this one](https://github.com/enolgor/wow-addon-tiptac/blob/3f9dc82db40b566aaa17d1a22306d8d1593c2d83/TipTac/ttCore.lua#L822).

But no success for the moment. I will need some help if someone has more time.

**Comment by Pingumania** [comment]
These are the changes I made to the ttCore.lua. Seems to be working.
```lua
hooksecurefunc("SharedTooltip_SetBackdropStyle",function(self)
	tt:ApplyBackdrop(self)
end)

function tt:ApplyBackdrop(tip)
	tip:SetBackdrop({
		bgFile = cfg.tipBackdropBG,
		edgeFile = cfg.tipBackdropEdge,
		tile = false,
		tileEdge = false,
		edgeSize = cfg.backdropEdgeSize,
		insets = { left = cfg.backdropInsets, right = cfg.backdropInsets, top = cfg.backdropInsets, bottom = cfg.backdropInsets },
	})
	tip:SetBackdropColor(unpack(cfg.tipColor))
	tip:SetBackdropBorderColor(unpack(cfg.tipBorderColor))
end
```

**Comment by enolgor** [comment]
Please check the fix I pushed, it should work now. I adapted from [the correct wow ui source](https://github.com/Gethe/wow-ui-source/blob/7d588020e0839cc849f5166317d77539af36d64d/SharedXML/SharedTooltipTemplates.lua#L51) the call to SetBackdropStyle because it did more things.

I think the key thing was hooking it or something... if somebody could throw more insight would be appreciated since I'm mostly working blind, I never developed an addon or did any Lua code 🤣

**Comment by Thrayl** [comment]
![image](https://user-images.githubusercontent.com/68885894/96368457-9d368400-119f-11eb-82a4-e45407b1d422.png)

The fix is good, however it had some unintended consequences..

**Comment by enolgor** [comment]
I'm not sure if that issue is related with the backdrop issue that we tried to fix.
That issue you have is it maybe related with your config? Can you try to tweak the insets and edge sizes so it looks better maybe?

**Comment by Thrayl** [comment]
![image](https://user-images.githubusercontent.com/68885894/96368600-4ed5b500-11a0-11eb-8008-c7a86ef4a9e1.png)

Thats with all settings reverted to default. I believe that the inset tooptips (tooltips within tooltips) are a different function.

**Comment by Thrayl** [comment]
Also, the tooltip borders are seemingly not on the correct strata

![image](https://user-images.githubusercontent.com/68885894/96368655-c4418580-11a0-11eb-83cc-a1d7247737a4.png)

In 8.3 these were a solid colour, now they are almost impossible to see.

**Comment by enolgor** [comment]
> ![image](https://user-images.githubusercontent.com/68885894/96368600-4ed5b500-11a0-11eb-8008-c7a86ef4a9e1.png)
> 
> Thats with all settings reverted to default. I believe that the inset tooptips (tooltips within tooltips) are a different function.

Ok now I can reproduce it. Whoever I believe this is a different issue than abling to change background colors, please if you could add a different issue with these images and a correct title it would be better in order to track them.

About the tooltip borders, I'm able to put solid borders with solid colours so not sure what you are referring here. Anyway, it should also be a separate issue since this one is about borders/backgrounds not updating.

**Comment by Thrayl** [comment]
Added as new issues. feel free to close this one out. Good work by the way!
