### ISSUE TITLE
Tooltips blank during combat and at other times

### ISSUE THREAD

**Issue by vladimirgluten** [enolgor/wow-addon-tiptac#17]
I'm having an issue where when I hover over one of my abilities during combat, the tooltip is just a blank box.  I also have the same issue when hovering over any mounts I have added to my action bars, just a big blank box.  This was actually an issue before pre-patch.  I tried deleting my saved variables for TipTac, that did reset everything but alas, the problem still exists.

**Comment by enolgor** [comment]
It seems that this is an issue that only happens to you.
You do not provide information on how to duplicate.
This repository, and the work that I and others are doing is to adapt this addon for Shadowlands because the original author is radio-silent.
But we are not the addon maintainers, we just do quick fixes, so if this is an issue that you had before 9.0.1 it seems like there is no point on investigating this issue.
